alias gh='history | grep '
alias con='~/Desktop/ServerConnect.sh'
alias ds='cd ~/Desktop'
alias ..='cd ..'
alias ...='cd ../../../'
alias ....='cd ../../../../'
alias .....='cd ../../../../'
alias .4='cd ../../../../'
alias .5='cd ../../../../..'
alias c='clear'
alias ls='ls --color=auto'

